### ISSUE TITLE
Opprettelse av Dialogelement

### ISSUE THREAD

**Issue by hjendal** [elsand/elsand.github.io#10]
Kunne det vært en ide at dialogelement først blir laget etter at virksomhet har utført sin endring? Reduserer antall handlinger mot "Dialogporten".

[anchor_id="sekvensdiagram-3"]

**Comment by AnneLiseFurmyr** [comment]
Høres ut som en god idee - dermed unngår man også at det blir liggende "tomme" dialoger på Dialogporten hver gang er bruker startet en tjeneste, men ikke gjorde eller lagret noe.

**Comment by elsand** [comment]
Tenker disse sekvensdiagrammene behøver å være noe tjenestetilbydere må følge til punkt og prikke, men heller indikerer et typisk integrasjonsmønster. Det vil jo ikke være noe som hindrer en tjenestetilbyder å avvente å opprette et element til etter at virksomheten/personen har oppgitt en eller annen mengde med informasjon som vil være hensiktsmessig å ta vare på, men jeg ser også for meg at det i mange tilfeller vil være en "endring" nok i seg selv og bare starte en tjeneste hos en gitt tilbyder slik at det er nyttig for vedkommende (eller andre i virksomheten) og finne igjen elementet i Dialogporten umiddelbart.
