### ISSUE TITLE
Sluttbruker initiert dialog gjennom API

### ISSUE THREAD

**Issue by hjendal** [elsand/elsand.github.io#11]
Hadde det vært lurt å ta en diskusjon på sekvensdiagrammene på både med og uten instansiering? Er det en mulighet for å forenkle sekvensdiagrammet ved at man avventer med å opprette et dialogelement til senere i prosessen?
Tror ikke vi har diskutert ferdig hvordan en SBS teknisk går fram for å kalle et API. Det vil si hvilken funksjonalitet API katalogen tilbyr etc. og hva som skal til for å sikre at API "alignes" tilfredsstillende slik at det ikke blir unødvendig komplekst for leverandørene.

[anchor_id="gjennom-api"]

**Comment by AnneLiseFurmyr** [comment]
Ja, høres ut som en god ide å gå gjennom dette. Vi tenker i utgangspunktet at det er bedre med direktekall til tjenesteeier som "master" for tilstand og dette løskobler komponentene mer og fungerer også når Dialogporten er «nede». Men obs: hvem skal da generer ID for et dialogelement? Ref tilsvarende endring i beskrivelse for tjenesteeier initiert dialog hvor dialogporten returnerer ID for et nyopprettet DE.  Hva skal SBS ha et forhold til: DE-ID eller ID på tjenesteelement hos tjenesteeier, eller begge? Bør de være like? Dette må ha sammenheng med EventAPIet, +?.
Og merk:  steg 4-7 i beskrivelsen er en relativ kompleks med 2-veis avhengighet og «potensiell låsesituasjon-» i kall fra Dialogport til TE som venter på retur av ID på eget DE – unødvendig?  Bedre med løsere koblinger 1 vei: kun fra TE til Dialogport?

**Comment by elsand** [comment]
Ja, det er noen avveininger her. Med direktekall får man en løsere kobling, men det legger en del kompleksitet over på tjenestetilbyder knyttet til autorisasjonskontroll som ellers vil kunne håndteres av Dialogporten. Koblingen blir kanskje _vel_ løs også, slik at SBS-et ikke får noe forhold til elementet som ligger i Dialogporten. Dette vil kunne føre til at det vil oppleves veldig ulikt å integrere mot en tjeneste avhengig av hvem som initierer dialogen.

**Comment by elsand** [comment]
Har gjort justeringer som jeg tror vil håndtere identifikator-problematikken, med at tilbyder kan oppgi UUID som identifikator.
