### ISSUE TITLE
Tilgang til Dialogelement

### ISSUE THREAD

**Issue by hjendal** [elsand/elsand.github.io#12]
For NAVs del vil det kunne være behov for å kunne få tilgang til alle Dialogelementer som er knyttet til NAV slik at vi kan spegle disse på NAVs side for arbeidsgivere. Hvilken vei en arbeidsgiver kommer inn til det offentlige kan variere, så dersom NAV kan spegle disse Dialogelementene så vil bruker oppleve å se det samme uavhengig av hvilken vei man går inn.

[anchor_id="dialogelement-de"]

**Comment by hjendal** [comment]
Og når det er flere flater som skal kunne vise et dialogelement så påvirker dette hvordan vi bør styre tilang til disse.

**Comment by elsand** [comment]
Jeg har skrevet mer om dette i avsnittet Autorisasjon. Det legges opp til at tjenestetilbydere får tildelt et eget Maskinporten-scope som gir tilgang til API-er som lar dem hente ned (og endre på) alle dialogelementer den har opprettet.
