### ISSUE TITLE
Sekvensdiagrammer

### ISSUE THREAD

**Issue by hjendal** [elsand/elsand.github.io#13]
Veldig bra dette :-)

Tror det utover i januar hadde vært nyttig å ha dedikerte møter hvor vi prater oss igjennom ett og ett sekvensdiagram og blir enige om justering, noterer hva som er uavklart og eventuelle uenigheter som det bør jobbes med.

[anchor_id="introduksjon"]

**Comment by elsand** [comment]
Ja, vi bør nok vie sekvensdiagrammene mer oppmerksomhet. Som jeg nevnte i en annen issue er det imidlertid ikke tenkt at disse skal beskrive den eneste måten en gitt integrasjon kan bygges på, men mer illustrere noe av mulighetsrommet uten å være uttømmende. Men de er nyttige for å identifisere bindinger som bør ses på (som diskusjonen med ID-er er et godt eksempel på).
