### ISSUE TITLE
Navngiving "Dialogport" versus "Dialogboks"

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#15]
Vi er litt usikre på navnet Dialogport, gitt at verdien av løsningen ikke nødvendigvis ligger i at det er en felles "port" som alle/alt skal gjennom, men heller en felles  samling og håndtering av digitale dialogtjenenster på tvers av flater og tjenensteeiere. 

[anchor_id="dialogporten"]

**Comment by elsand** [comment]
Ser det poenget. Navngivning er som kjent vanskelige greier, og jeg tror kanskje ikke vi trenger å finne ut hva dette til syvende og sist skal hete bare vi inntil videre er enige om hva "Dialogporten" faktisk betyr. Så er det sikkert noen kommunikasjonsfolk både hos oss og dere som vil ha et ord med i laget etterhvert :) 

(For moro skyld spurte jeg ChatGPT om forslag for en stund siden, synes det var et par ålreite (om kanskje litt vel unorske) forslag den kom med: https://imgpile.com/images/dwl3k2.png :)
