### ISSUE TITLE
Tydeliggjøring av hva produktet er / omfatter

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#16]
Bør siste setning justeres litt for å tydeliggjøre selve løsningen/produktet - f.eks. noe slikt:  «Dialogporten benyttes også som navn på løsningskomponenten (produktet) som tilbyr API for enhetlig tilgang og håndtering av digitale dialoger til Felles Arbeidsflate(r) og Sluttbrukersystemer, inkludert lagring av metadata om dialogene, og som dekker Altinn Platform-funksjonalitet for tilgangsstyring og -kontroll, hendelser og varsling».

[anchor_id="dialogporten"]

**Comment by elsand** [comment]
Høres bra ut, har lagt inn den formuleringen :)
