### ISSUE TITLE
Digitale dialoger kan være 

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#17]
Til listepunkt 3: sending av digital post – siste kulepunkt «Teknisk/funksjonelt subset av tjenestetilbyder-initiert dialog.»  -->  melding til parten/bruker (f.eks. digital post) er ofte en del av (subset) av begge typene ovenfor, altså også som et svar i en Sluttbruker-initiert dialog.  
En dialog kan også omfatte begge de to scenarioene, altså at det er mulig å initiere den både fra tjenesteeier og fra Sluttbruker - bør det nevnes til slutt? 

[anchor_id="scenarioer-som-påvirker-dialogporten"]

**Comment by elsand** [comment]
Jeg la inn en presisering i siste kulepunkt.

(Forresten så er den hacka-i-hop innebygginga av issues i dokumentet som du sikkert har merket langt fra feilfri - her ser jeg escapinga av "å" i anchor-id-taggen gjør at den ikke dukker opp i dokumentet).
