### ISSUE TITLE
Dobble piler for endring av tjenesteressurs?

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#20]
Under overskriften "Mutering (oppdatering) av dialogelement" kommer på nytt stiplede piler for oppdatering av tjenesteressurs. Er dette en copy/paste feil og skal fjernes? Hvis ikke bør det forklares i teksten nedenfor hvorfor de er oppført på nytt - dette kan selvfølgelig skje, men hører vel egentlig ikke til standardløpet for oppdatering av et dialogelement? 

[anchor_id="opprettelse-av-dialogelement"]

**Comment by elsand** [comment]
Copy-paste feil ja. Dette er nå rettet.
