### ISSUE TITLE
Validering av opak token

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#21]
Validering av sesjonstoken gjøres av dialogporten i denne figuren  – dette blir vel feil, dialogporten har vel ikke noe forhold til brukerens sesjon?  Ref også tekst under sekvensdiagrammet på steg 4 kulepunkt 2: "Når tjenestetilbyder mottar forspørsel fra nettleser, gjøres et bakkanal-oppslag mot Dialogporten tjenestetilbyder-API hvor sesjonstoken oppgis. Returnerer en modell som forteller autentisert part (f/dnr, orgnr), 
valgt aktør, ...."

[anchor_id="konsum-gjennom-gui-portal"]

**Comment by elsand** [comment]
Diagrammet viser at tjenestetilbyder gjør oppslag mot Dialogporten for å verfisere et opak token, og den tekstlige beskrivelsen nevner både bruk av self-contained og opak token.

Har nettopp lagt inn en del mer tekst rundt bruk av token, og tenker at bruk av opak token er noe som antagelig ikke blir hensiktsmessig, så skal fjerne dette.
