### ISSUE TITLE
Felles Arbeidsflate som eksempel

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#22]
Felles Arbeidsflate er et konkret eksempel på GUI-basert bruk av Dialogport-APIet, dvs. at det kan finnes andre typer GUI-klienter på lik linje - bør vi skrive det tydelig er sted, f.eks. over sekvensdiagrammene for GUI-basert bruk?  

[anchor_id="konsum-gjennom-gui-portal"]

**Comment by elsand** [comment]
Jeg mener dette er presisert i avsnittet https://elsand.github.io/dialogporten.html#felles-arbeidsflate , men kan legge inn en ytterligere notis om dette over diagrammene.
