### ISSUE TITLE
Sjekk mot Dialogport om allerede påstartet dialog unødvendig?

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#24]
Opt steg 3: bakkanal kall for sjekk om det finnes allerede påstartet dialog -> denne trengs vel ikke, tjenesteeier er «master» og skal alltid ha fasiten? 

[anchor_id="tekstlig-beskrivelse-av-trinn-3"]

**Comment by elsand** [comment]
Enig, fjerner.
