### ISSUE TITLE
Asynk oppdatering av Dialogport og løsere kobling 

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#25]
Generelt sett tenker jeg det er bedre at Dialogporten oppdateres asynk i etterkant, og ikke underveis, for å få en løsere kobling. 
Må ellers passe på transaksjonskontekst (boundary) - Event kan først fyres av når både tjeneteinstans hos TE og DE hos dialogport finnes og gjensidig referer hverandre. Bedre at TE er "master" og generer tjenesteinstans med ID og bestemmer ID for Dialogelement også (samme?)?  (ellers må TE mellom steg 5 og 6 kalle Dialogport for å signalisere at kobling mellom Tjenensteinstans og DE er opprettet og klar til at event kan sendes...). 

[anchor_id="variant-uten-instansierings-api"]

**Comment by elsand** [comment]
> Event kan først fyres av når både tjeneteinstans hos TE og DE hos dialogport finnes og gjensidig referer hverandre.

Godt poeng.

> Bedre at TE er "master" og generer tjenesteinstans med ID og bestemmer ID for Dialogelement også (samme?)?

Det kan vi se på. Vi er avhengig av å ha id-er som vi vet er globalt unike, ikke kan gjettes, har samme format og er egnet for databaseindeksering slik at en unngår fragmenteringen som er typisk for helt random GUIDs, og aller helst gir oss mulighet til å sortere kronologisk uten en ekstra indeks. (Rent teknisk har vi sett på bruke COMB-verdier, ala det som beskrives på https://github.com/richardtallent/RT.Comb/)

Hvorvidt en tjenestetilbyder-oppgitt ID er høvelig kan kanskje valideres ved opprettelse, og at man har dokumentasjon (og tilbyr biblioteker ala det over) som gjør det enkelt for tjenestetilbydere og lage generere ID-er som kan brukes. Dialogporten kan tom. tilby et eget lettvekts API i Dialogporten som bare genererer ID-er i ønsket format som garantert vil være brukbare.

Ellers mangler diagrammet et potensielt kall mellom TE og Dialogporten før "Oppretter tjenesteinstans" for å validere at vedkommende faktisk er autorisert. Her er det kanskje en høyere risiko for mismatch mellom hva som blir lagt til grunn i Dialogporten (og dermed i Felles arbeidsflate) og hos tjenestetilbyder enn om Dialogporten gjennom et felles instansierings-API hadde håndtert dette.

**Comment by elsand** [comment]
Etter å ha sett en del nærmere på dette ser jeg at det blir teknisk vanskelig å skulle overlate til andre å bestemme ID-er som skal ha de egenskapene som nevnt i forrige kommentar. Med å innføre en mekanisme for å "halvveis" lagre elementet vil man kunne implementere en synkroniseringsprotokoll som er atomisk (sett fra "party" sitt ståsted). Har oppdatert diagrammet til å reflektere dette.

**Comment by elsand** [comment]
Ref. diskusjonen vi hadde på møtet i dag, så oppfatter jeg at det er to konkrete alternativer vi må fatte et valg på mht identifkatorer:

* Bruke UUIDv4, og la tjenestetilbydere oppgi denne ved opprettelse av dialogelementet
   * Fordeler: enkelt å generere, kan genereres uavhengig, reduserer kompleksitet
   * Ulemper: random ID-er gir ytelsesutfordringer knyttet til fragmentering av B+Tree / clustered indekser på skala, trenger ytterligere en indeks for kronologisk sortering
 * Bruke COMB / TSID / ULID, som genereres av Dialogporten
   * Fordeler: unik og kan ikke gjettes/iterereres samtidig som indeksproblemer unngås, kronologisk sortering
   * Ulemper: kompliserer synkronisering av identifikatorer, vil fort lede til at SBS-er må forholde seg til både Dialogportens og tjenestetilbyders ID

Altinn 3 forøvrig benytter UUIDv4 for instanser, og jeg er usikker på hvorvidt man har vurdert de nevnte ytelsesaspektene. Jeg har heller ingen harde tall på dette, så det kan hende min bekymring er uberettiget. Innser også at synkroniseringsproblematikken her er høyst reell, og gjør det vanskeligere for tjenestetilbydere å gjøre dette "rett" og unngå at SBS-er må forholde seg til flere ID-er. Jeg heller nok derfor mot å bare bruke UUIDv4.

Andre tanker?

(@AnneLiseFurmyr usikker på om Erik har en github-konto som kan tagges her?)

cc @altinnadmin

**Comment by elsand** [comment]
@erik-nygren

**Comment by erik-nygren** [comment]
Jeg mener også at ulempene som du skisserer veies opp av fordelene med uuid. Det finnes også nyere versjoner av uuid som skal adressere noe av det du er inne på, men usikker på støtten for dette rundt omkring. Vi benytter uuid soim nøkkel i en del sammenhenger med temmelig stort volum. UUID har også sikkerhetsmessige fordeler (kan ikke "gjettes"), men her oppfatter jeg uansett ikke at sekvensnumre var aktuelle identifikatorer.

**Comment by elsand** [comment]
@AnneLiseFurmyr @erik-nygren 
Ref diskusjonene over har jeg endret i teksten og diagrammene til å støtte at tjenestetilbydere kan oppgi identifikator.
