### ISSUE TITLE
Ressurs-orientert navngiving av API

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#26]
Bedre å velge mer "ressurs"-orientert navngiving på APIet?  F.eks. dialogporten.no/dialogelement/{id} osv. 

[anchor_id="openapi"]

**Comment by elsand** [comment]
Enig, har endret. Har forøvrig vekslet mellom "dialogue" og "dialog" i engelsk/teknisk sammenheng, men tror jeg begynner å helle mot sistnevnte.
