### ISSUE TITLE
Multiple audiences versus tokeninnveksling

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#27]
Ref. steg 2: vi bør vurdere hvordan slik kall-serier skal løses:  mutiple audiences for et token versus innveksling av tokens

[anchor_id="tekstlig-beskrivelse-av-trinn-2"]

**Comment by elsand** [comment]
Jeg har skrevet litt om dette i avsnittet Autorisasjon. Dialogporten vil ikke kreve/sjekke aud-claims, og vil ikke hindre at klienter henter ut tokens med flere scopes og evt. aud-claims hvis man ønsker å bruke samme token mot både Dialogporten og tjenestetilbyder. Dette vil dog gjør det mulig for tjenestetilbyderen å gjenbruke tokenet mot Dialgporten som om den var brukeren, og få tilgang til elementer fra andre tilbydere (replay attack). Ved bruk av dialogelementtokens (tidligere kalt sesjonstokens) vil man kunne unngå dette.
