### ISSUE TITLE
Generelle tema

### ISSUE THREAD

**Issue by AnneLiseFurmyr** [elsand/elsand.github.io#28]
Supert underlag og godt beskrevet konsept!  
Vi har et par generelle tema vi bør diskutere fremover:

- "Aktiv port" versus "passiv boks": Vår oppfatning er at løsningen (dialogport/dialogboks) ikke skal være en "port" som alt/alle skal gjennom. Det er et mål for oss at det er så løse koblinger som mulig mellom tjenesteeiers systemer (som er "master" for dialogenes innhold og status) og Dialogporten/Dialogboksen som holder på en asynkront oppdatert kopi av metadata om tjenesteinstansene (i form av et dialogelement).  Kall bør ikke gå via "porten" hvis det ikke gir en egen nytte/verdi?  F.eks. går oppslag på et dialogelement som tilhører en hendelse/event  alltid via Dialogporten, gir det verdi/mening? Alternativt kall direkte til URL til tjenesteinstans hos tjenesteeier. 
--> Tankekors til diskusjon: blir modellen med kombinasjonen direkte til TE eller via DialogPort *for* kompleks, og kan dette forenkles?

- Vi må se på sammenhengen til dagens Instances-API på Altinn3 - det er lite hensiktsmessig for de som bruker dette i dag at det lages noe helt nytt på siden? Og den nye Dialogport erstatter vel (langt på vei) behovet? 

-	Noen steder nevnes «subressurs» - hvordan er sammenhengen mellom TjenesteRessurs og Subressurs <-> handling?  
«Er gjenstand for autorisasjon definert av referert tjenesteressurs og eventuell subressurs. F.eks. vil f.eks. “Signer” kunne kreve andre rettigheter avhengig av policy knyttet til tjenesteressursen.»

-	Vi må jobbe litt mer med hvilke handlinger og statuser som er forhåndsdefinert (og evt. "standard"/default" og hvilke som «tilhører» og/eller tolkes av hvilke komponenter - dette tas fra det funksjonelle arbeidet som går i parallell.  
     o	       f.eks. står det innledningsvis under begrepsforklaringen «GUI handlinger» at det kun er  «slett»  som Dialogporten har knyttet semantikk til. Vi er usikre om det bør kunne slettes fra Dialogporten. 
      o	Eksempler på handlinger under 1. sekvensdiagram – steg 2 “Åpne”, “Arkiver”, “Slett”, “Bekreft”, “Signer”, “Betal”, “Les mer”, etc.  --> arkiver er en handling som kun Arbeidsflaten har et forhold til?   (under 2. sekvensdiagram nevnes «arkivering» i steg 6) 
    o	Eksempler på status Status 1. sekvensdiagram – steg 2  (“under utfylling”, “klar til signering”, “venter på andre”, “venter på svar fra tjenestetilbyder” etc)

- Api 'ene for dialoger må være utvidbare uten at det påvirker de som allerede har tatt det i bruk (vi ønsker jo på sikt å jobbe med omnikanal, legge på nye "standard" handlinger / status, se på støtte for sammenhengende tjenester etc. fremover?)

[anchor_id="introduksjon"]

**Comment by elsand** [comment]
(Vi diskuterte mye av dette på møtet, men legger inn kommentarene jeg hadde påbegynt før møtet)

> "Aktiv port" versus "passiv boks"

Jeg tror vi er prinsipielt enige. Ingen kall vil trenge å gå via (i betydning proxy-ing) Dialogporten med mindre vi ser klare fordeler. Jeg mener dog det er noen fordeler knyttet til bl.a. instansiering (ref diskusjonen i #25), og enkelte typer GUI-actions som ikke krever mer interaksjon enn å trykke på en knapp vil kunne gi bedre brukskvalitet med å gå gjennom bakkanal i stedet for at brukeren omdirigeres i nettleser frem og tilbake. DIrektekall fra SBS til tjenestetilbyder (f.eks. som følge av en event) uten å ha vært innom Dialogporten for å hente actions og/eller dialogelementtoken innebærer en annen logikk knyttet til bl.a. tilgangskontroll, hvor tjenestetilbyder basert på kun et Maskinporten/ID-porten-token må gjøre oppslag for å sjekke autorisasjon. 

Imidlertid står tjenestetilbyderen fritt til å ta i bruk disse mekanismene etter eget forgodtbefinnende. De nevnte oppslags-API-ene for autorisasjon må vi uansett etablere, og det vil kunne være hensiktsmessig å bruke dem direkte i mange tilfeller.

> Vi må se på sammenhengen til dagens Instances-API på Altinn3

Ambisjonen er at alle Altinn3-instanser også skal være tilgjengelig via Dialogporten på samme måte som tjenesteinstanser hos Skatt, NAV og andre. Instances-API-et vil kunne leve parallelt, og vil kunne videreutvikles med ytterligere Altinn-spesifikk funksjonalitet som eksisterer parallellt med Dialogportens API-er som bestreber å være generiske. Jeg tror dog at det i de fleste tilfeller vil være hensiktsmessig å legge opp til SBS-er gjør sine integrasjoner mot Dialogporten i stedet for instances-API-et, og at instances-API-et da ender opp med å være primært et API for tjenesteeierene i Altinn3 som benyttes for å hente innsendinger.

> hvordan er sammenhengen mellom TjenesteRessurs og Subressurs <-> handling?

Dette trenger en bedre beskrivelse i dokumentet, men det henger sammen med at en XACML-policy består av regler som omfatter tre ting - et subjekt, en ressurs og en handling. Hver tjenesteressurs inneholder metadata som beskriver tjenesten, samt én XACML-policy som kan inneholde et vilkårlig sett med regler. Opprinnelig var det tenkt at alle disse reglene skulle gjelde en og samme ressurs - og jeg tror at man i de fleste tilfeller vil klare seg med det - men jeg ser behovet for et ytterligere nivå med tilganggstyring - f.eks. om det skal være ulike tilgangsregler for ulike vedlegg eller ulike regler for samme type handling men på ulike tidspunkt/steg/tilstander i tjenesten. 

Jeg skal forsøke å skrive litt mer rundt dette og legge inn "ressurs" / "subressurs" i begrepsoversikten.

> Vi må jobbe litt mer med hvilke handlinger og statuser som er forhåndsdefinert 

Det kan nok være hensiktsmessig å beskrive noen standarder her, men jeg tror ikke Dialogporten eller Felles arbeidsflate nødvendigvis trenger å behøve å "forstå" hva de ulike handlingene er for noe. Det eneste unntaket jeg ser for meg er "Slett", som i GUI-sammenheng typisk er forbundet med logikk som f.eks. en "Er du sikker?"-prompt og fjerning av elementet. "Arkivering" er egentlig et litt dårlig eksempel, fordi det handler egentlig om å flytte et element fra en liste til en annen. Dette er noe som tjenestetilbyder egentlig ikke trenger å ha noe med, og det bør kunne være opp til virksomheten/brukeren å organisere sin "boks" etter eget forgodtbefinnende - på samme måte som en organiserer mapper/filtre i Outlook.

Statuser tenker jeg imidlertid i større grad bør defineres, og det er lagt inn et forslag i JSON request-modellen. Disse har vi ikke snakket så mye om, så det bør vi nok se litt nærmere på, og diskutere hvorvidt vi skal støtte custom statuser og hvordan disse eventuelt skal håndteres i Felles arbeidsflate.

> Api 'ene for dialoger må være utvidbare 

Ja, vi må ha god API management her for å kunne introdusere endringer (herunder ikke-bakoverkompatible endringer) i API-et.

**Comment by elsand** [comment]
(Vi diskuterte mye av dette på møtet, men legger inn kommentarene jeg hadde påbegynt før møtet)

> "Aktiv port" versus "passiv boks"

Jeg tror vi er prinsipielt enige. Ingen kall vil trenge å gå via (i betydning proxy-ing) Dialogporten med mindre vi ser klare fordeler. Jeg mener dog det er noen fordeler knyttet til bl.a. instansiering (ref diskusjonen i #25), og enkelte typer GUI-actions som ikke krever mer interaksjon enn å trykke på en knapp vil kunne gi bedre brukskvalitet med å gå gjennom bakkanal i stedet for at brukeren omdirigeres i nettleser frem og tilbake. DIrektekall fra SBS til tjenestetilbyder (f.eks. som følge av en event) uten å ha vært innom Dialogporten for å hente actions og/eller dialogelementtoken innebærer en annen logikk knyttet til bl.a. tilgangskontroll, hvor tjenestetilbyder basert på kun et Maskinporten/ID-porten-token må gjøre oppslag for å sjekke autorisasjon. 

Imidlertid står tjenestetilbyderen fritt til å ta i bruk disse mekanismene etter eget forgodtbefinnende. De nevnte oppslags-API-ene for autorisasjon må vi uansett etablere, og det vil kunne være hensiktsmessig å bruke dem direkte i mange tilfeller.

> Vi må se på sammenhengen til dagens Instances-API på Altinn3

Ambisjonen er at alle Altinn3-instanser også skal være tilgjengelig via Dialogporten på samme måte som tjenesteinstanser hos Skatt, NAV og andre. Instances-API-et vil kunne leve parallelt, og vil kunne videreutvikles med ytterligere Altinn-spesifikk funksjonalitet som eksisterer parallellt med Dialogportens API-er som bestreber å være generiske. Jeg tror dog at det i de fleste tilfeller vil være hensiktsmessig å legge opp til SBS-er gjør sine integrasjoner mot Dialogporten i stedet for instances-API-et, og at instances-API-et da ender opp med å være primært et API for tjenesteeierene i Altinn3 som benyttes for å hente innsendinger.

> hvordan er sammenhengen mellom TjenesteRessurs og Subressurs <-> handling?

Dette trenger en bedre beskrivelse i dokumentet, men det henger sammen med at en XACML-policy består av regler som omfatter tre ting - et subjekt, en ressurs og en handling. Hver tjenesteressurs inneholder metadata som beskriver tjenesten, samt én XACML-policy som kan inneholde et vilkårlig sett med regler. Opprinnelig var det tenkt at alle disse reglene skulle gjelde en og samme ressurs - og jeg tror at man i de fleste tilfeller vil klare seg med det - men jeg ser behovet for et ytterligere nivå med tilganggstyring - f.eks. om det skal være ulike tilgangsregler for ulike vedlegg eller ulike regler for samme type handling men på ulike tidspunkt/steg/tilstander i tjenesten. 

Jeg skal forsøke å skrive litt mer rundt dette og legge inn "ressurs" / "subressurs" i begrepsoversikten.

> Vi må jobbe litt mer med hvilke handlinger og statuser som er forhåndsdefinert 

Det kan nok være hensiktsmessig å beskrive noen standarder her, men jeg tror ikke Dialogporten eller Felles arbeidsflate nødvendigvis trenger å behøve å "forstå" hva de ulike handlingene er for noe. Det eneste unntaket jeg ser for meg er "Slett", som i GUI-sammenheng typisk er forbundet med logikk som f.eks. en "Er du sikker?"-prompt og fjerning av elementet. "Arkivering" er egentlig et litt dårlig eksempel, fordi det handler egentlig om å flytte et element fra en liste til en annen. Dette er noe som tjenestetilbyder egentlig ikke trenger å ha noe med, og det bør kunne være opp til virksomheten/brukeren å organisere sin "boks" etter eget forgodtbefinnende - på samme måte som en organiserer mapper/filtre i Outlook.

Statuser tenker jeg imidlertid i større grad bør defineres, og det er lagt inn et forslag i JSON request-modellen. Disse har vi ikke snakket så mye om, så det bør vi nok se litt nærmere på, og diskutere hvorvidt vi skal støtte custom statuser og hvordan disse eventuelt skal håndteres i Felles arbeidsflate.

> Api 'ene for dialoger må være utvidbare 

Ja, vi må ha god API management her for å kunne introdusere endringer (herunder ikke-bakoverkompatible endringer) i API-et.
