### ISSUE TITLE
Tilsvarende systemer hos NAV

### ISSUE THREAD

**Issue by peterbb** [elsand/elsand.github.io#31]
Det er kanskje interessant for deg og se to av NAVs systemer som ligner veldig. Mulig at Håkon Jendal allerede har delt disse med deg, men her er de:
- https://navikt.github.io/arbeidsgiver-notifikasjon-produsent-api/ (rettet mot arbeidsgivere, tilgangsstyrt på enkeltrettigheter og NAV-interne registre)
- https://navikt.github.io/brukernotifikasjon-docs/ (til personbrukere, tilgangsstyrt på fnr)

Begrepsoversettelse blir noe sånt som:
- Dialogelement ~ beskjed, oppgave
- Dialoggruppe ~ sak (men brukernotifikasjoner har gått bort fra saker/dialoggrupper tror jeg)

[anchor_id="introduksjon"]

**Comment by elsand** [comment]
Takk for lenkene. Håkon har fortalt om dette, men jeg har ikke sett på detaljene. Nyttig å se på hvorvidt systemene og tilhørende begreper/mekanismer er aligned og kan naturlig mappes til hverandre uten altfor mye akrobatikk 😊
