### ISSUE TITLE
Tilgangsstyring "internt" for store tjenestetilbydere

### ISSUE THREAD

**Issue by peterbb** [elsand/elsand.github.io#32]
For større tjenestetilbydere som NAV, så tenker jeg det er uheldig å ikke ha noe mer finkornet tilgangsstyring på API-et som tjenestetilbydere bruker. Altså hvis én NAV-tjeneste blir hacket, så er dumt om dialogporten kan bruke for å lekke dialoger for helt urelaterte tjenester.

I NAVs notifikasjonsplattform for arbeidsgiver (https://navikt.github.io/arbeidsgiver-notifikasjon-produsent-api/) så er produsenter tilgangsstyrt på "merkelapper", slik at de ikke kan se dialogen til andre team. Samtidig ser jeg på https://app.swaggerhub.com/apis-docs/Altinn/Dialogporten/0.0.1 at det ikke er noe måte å liste opp eller søke etter dialoger: om det er et bevisst valg, så hjelper jo det betydelig.

[anchor_id="tjenestetilbyder"]

**Comment by elsand** [comment]
Godt innspill, enig i at dette er uheldig. Søke/liste-APIet er tenkt å skulle være tilgjengelig også for tjenestetilbydere, så dette er noe vi må finne noen tiltak for å mitigere risiko rundt. Det å kreve et separat Maskinporten-scope for tilgang til søke/liste-APIet for tjenestetilbydere er nærliggende, men i tillegg trenger vi en "tilbyder-selvpålagt" mekanisme for beskrankning - noe ala merkelapp-tilnærmingen du refererer. Dette kan løses med at vibutvider "configuration"-modellen med et felt som definerer ytterligere (vilkårlige) scopes som tjenestetilbyder må ha i oppgitt Maskinporten-accesstoken for å kunne aksessere det aktuelle elementet. Dette gjør at tjenestetilbyder selv kan granulere  egne systemers tilgang til Dialogporten etter eget ønske.

På sluttbrukersiden er behovet for granulert tilgang løst med systemressurs/XACML, så en tilsvarende mekanisme for sluttbruker-API-konsumenter i Dialogporten tror jeg ikke er nødvendig/hensiktsmessig. Hva tjenestetilbyder-APIene krever av sluttbrukersystemene mht evt ytterligere autorisasjonsmidler er imidlertid ikke noe Dialogporten trenger å legge seg borti.
