### ISSUE TITLE
Ang Dialogporten-spesifikke claims

### ISSUE THREAD

**Issue by sivaglen** [elsand/elsand.github.io#33]
Skal ikke token inneholde informasjon om hvem virksomhetsbruker er  (altsåsystemidentitet i Altinn med tildelte rettigheter som gir tilgang til tjenesteressursen), 

[anchor_id="dialogporten-spesifikke-claims"]

**Comment by elsand** [comment]
Det er med denne tilnærmingen ikke nødvendig, siden tokenet inneholder et claim for dialog-id-en og hvilke actions ihendehaveren av tokenet er autorisert for. Tjenestetilbyder vil derfor ikke ha behov for å gjøre noen oppslag for å håndheve autorisasjon.
