### ISSUE TITLE
Synkron oppdatering av DBE

### ISSUE THREAD

**Issue by elsand** [elsand/elsand.github.io#4]
Usikker på om det er en god idé å tilby en mekanisme for å foreta et synkront oppslag for å refreshe dialogbokselementet ved åpning, i stedet for å legge opp til at tjenestetilbyder alltid må selv sørge for å holde elementet oppdatert. Førstnevnte skaper hardere bindinger til eksterne endepunkter, og vil ha teknisk/praktiske konsekvenser som i noen tilfeller - f.eks. et SBS som itererer gjennom og åpner mange elementer - kan ha negativ innvirkning på tilgjengelighet.

[anchor_id="dialogelement-de"]

**Comment by hjendal** [comment]
Enig at det må legges opp til at man kan unngå harde bindinger så langt det er mulig. Det gjør løsningene mer robuste og gir høyere tilgjengelighet/oppetid.

**Comment by AnneLiseFurmyr** [comment]
Enig i at det er bedre at TE (tjenesteeier) holder Dialogelementene (DE) oppdatert (asynkront).

**Comment by elsand** [comment]
Har fjernet avsnittet og referansene til dette i JSON-eksemplene.
