### ISSUE TITLE
kommunikasjon ut til bruker 

### ISSUE THREAD

**Issue by hjendal** [elsand/elsand.github.io#5]
Bør definisjonen av Dialogtjeneste også inkludere kommunikasjon ut til bruker inkludert deling av informasjon med bruker, og ikke bare innhenting av informasjon? Ref scenarier som beskrives lengre ned på siden?

[anchor_id="dialogtjeneste"]

**Comment by elsand** [comment]
Har lagt til et lite avsnitt for dette.

**Comment by AnneLiseFurmyr** [comment]
Fint, bra at meldingstjenenster og informasjon som sendes til bruker/part inkluderes tydelig i beskrivelsen - den første setningen blir vel da litt for snever? :  "En dialogtjeneste er en digital tjeneste tjenestetilbyderen innhenter informasjon fra en part i forbindelse med forvaltning av et eller flere lovverk."  Se også beskrivelsen av "Tjenesteinstans" rett nedenfor - her står det bla.  "Tjenesteinstand refererer seg til en konkret dialog mellom en tjenestetilbyder og en eller flere parter, og som typisk refererer en saksgang eller prosess hos tjenestetilbyderen". 
Det blir litt uklart hva som er forskjellen og/eller sammenhengen mellom Dialogtjeneste og Tjenesteinstans, gitt at Dialogtjeneste i hovedsak beskrives som "innsamling av informasjon" mens Tjenesteinstans beskrives som ".. refererer seg til en konkret dialog mellom en tjenestetilbyder og en eller flere parter, og som typisk refererer en saksgang eller prosess hos tjenestetilbyderen". Jeg tror en del av beskrivelsen av Tjenesteinstans egentlig hører hjemme under Dialogtjeneste? Og så tror jeg vi kan/bør legge inn en informasjonsmodell slik vi begynte på før jul for å støtte teksten med en visuell fremstilling av begrepen ift hverandre?

**Comment by elsand** [comment]
Jeg la inn en justering i teksten ("innhenter informasjon fra" -> "kommuniserer med") for å bedre omfatte meldingstjenester. Usikker på hvorvidt det vil være klargjørende å flytte innhold (og eventuelt hva det skulle være) fra "instans" til "tjeneste". Kom gjerne med forslag :)
