### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by hjendal** [elsand/elsand.github.io#6]
Bruker bør oppleve SSO på tvers av Dialogporten og tjenestetilbyder. Det bør ikke bli slik det fungerer med Digipost og kommunene hvor man først logger seg på Digipost og så kommunen for å få tilgang til noe.

[anchor_id="dialogelementtoken-det"]

**Comment by elsand** [comment]
Enig, og siste setning i dette avsnittet forsøker å peke på at SSO i ID-porten vil være med på å sikre en sømløs oppleves for sluttbrukeren. Sesjonstokenet er noe som må embeddeds i URL-ene som benyttes ved omdirigering (eller f.eks. oppgis av SBS i en header) for å la tjenestetilbyderen enkelt kontrollere finkornet autorisasjon (altså at den gitte brukeren har tilgang til elementet som ble klikket, og dermed den relaterte tjenesteinstansen). Dette muliggjør at brukeren kan dyplenkes inn til dialogen hos tilbyder og fortsette uten friksjonen som skapes med ekstra klikk.
