### ISSUE TITLE
Pil med «administrer dialogelementer gjennom» for Altinn 3 App

### ISSUE THREAD

**Issue by hjendal** [elsand/elsand.github.io#7]
Pil med «administrer dialogelementer gjennom» for Altinn 3 App skal vel gå fra Altinn 3 App og ikke Digdir?

[anchor_id="overordnet-diagram-over-konsept"]

**Comment by elsand** [comment]
For Altinns del blir det muligens ikke appen i seg selv som administrerer dette, men at dette (integrasjonen med dialogporten) skjer transparent for appen og istedet håndteres av plattform-funksjoner. Tanken med å knytte pilen til virksomhetene og ikke de enkelte tjenestene er diagrammet da legger mindre føringer for hvordan akkurat dette håndteres hos den enkelte tjenestetilbyderen.
