### ISSUE TITLE
Sesjonstoken

### ISSUE THREAD

**Issue by hjendal** [elsand/elsand.github.io#8]
Figuren viser at man må gjøre et kall for å validere token. Bør vel være self contained token (eller hav det heter) slik at man ikke må gjøre dette kallet, men kan validere tokenet der og da?

[anchor_id="sekvensdiagram-1"]

**Comment by elsand** [comment]
I det (foreløpig slukne) avsnittet om sesjonstoken nevnes at både self-contained/transparent token og opake tokens i teorien kan benyttes her. Det er nok fordeler og ulemper med begge variantene som må utredes nærmere, men tenker også i utgangspunktet at det beste alternativet er self-contained - så jeg kan endre diagrammet til å reflektere det.
